### ISSUE TITLE
Cannot use Image on Tab

### ISSUE THREAD

**Issue by tannt275** [xmartlabs/XLPagerTabStrip#240] opened 2016-09-29 06:35 UTC
When i overide this method 
`func indicatorInfoForPagerTabStrip(pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return IndicatorInfo(title: "", image: UIImage(named: "tick_green"), highlightedImage: UIImage(named: "tick_green"))
    }`
In this tick_green is an image i add to Assets.xcassets of my Project
i got an error "fatal error: unexpectedly found nil while unwrapping an Optional value"
I don't know how to fix. Can you help me?

**Comment by robforsythe** [comment] 2016-10-16 20:28
+1

**Comment by PhilizSwiss** [comment] 2016-10-17 09:34
+1

**Comment by elementsrtyte** [comment] 2016-10-25 23:54
+1

**Comment by StanK23** [comment] 2016-10-28 09:53
its because ButtonCell.xib doesn't even contain imageView, but class have empty outlet for that. And when you trying to set image to not existed image view - it's crashed.
So, it's definetely not a bug, it is just not implemented for some reason :D

**Comment by PhilizSwiss** [comment] 2016-11-23 09:49
Any workaround for this ? How can I manage to have an icon instead of a text in the tab bar ? Thanks !!

**Comment by matthewbschneider** [comment] 2016-12-31 18:42
I found a quick and simple workaround by modifying the cell in configureCell override method:

`    func setTabImageView(frame: CGRect, image: UIImage) -> UIImageView {
        let imageView = UIImageView()
        
        imageView.frame = frame
        imageView.image = image
        imageView.image = imageView.image!.withRenderingMode(.alwaysTemplate)
        imageView.tintColor = .white
        imageView.contentMode = .scaleAspectFit
        
        return imageView
    }
    
    override func configureCell(_ cell: ButtonBarViewCell, indicatorInfo: IndicatorInfo) {
        super.configureCell(cell, indicatorInfo: indicatorInfo)
        
        let frame = CGRect(x: 0, y: 10, width: cell.bounds.width, height: 25)
        
        switch indicatorInfo.title {
        case "TAB_TITLE_1":
            cell.addSubview(setTabImageView(frame: frame, image: UIImage(named: "tab_icon_1")!))
            break
        case "TAB_TITLE_2":
            cell.addSubview(setTabImageView(frame: frame, image: UIImage(named: "tab_icon_2")!))
            break
        default:
            cell.addSubview(setTabImageView(frame: frame, image: UIImage(named: "alert")!))
        }
        
        for subview in cell.subviews {
            if subview.isKind(of: UILabel.self) {
                subview.removeFromSuperview()
            }
        }

        cell.backgroundColor = .clear
    }`

**Comment by ataibarkai** [comment] 2017-01-03 19:23
+1

**Comment by oktayayr** [comment] 2017-01-12 20:26
+1

**Comment by dmdque** [comment] 2017-01-18 20:23
+1

**Comment by jettandres** [comment] 2017-01-27 01:58
+1

**Comment by santiagofm** [comment] 2017-05-11 18:13
This issue is fixed on the master branch

Cheers

**Closed by santiagofm** 2017-05-11 18:13 UTC

**Comment by yberryDeveloper** [comment] 2017-09-21 10:12
**'Can't add self as subview'**
Please Have A Look on this image below.
https://ibb.co/gfj7EQ
