### ISSUE TITLE
XLPagerTabStrip crashing when self.view.layoutIfNeeded() is called

### ISSUE THREAD

**Issue by RyanHop3** [xmartlabs/XLPagerTabStrip#312] opened 2017-01-31 18:33 UTC
When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: XLPagerTabStrip 7.0, XCode 8.2.1, Swift 3

In the viewDidLoad of the XLPagerTabStrip View Controller I have tried to call `self.view.layoutIfNeeded()` which is causing the simulator to crash on:

`let fromFrame = layoutAttributesForItem(at: IndexPath(item: fromIndex, section: 0))!.frame` 
within the open func move from the buttonBarView class.

**Comment by fdoxyz** [comment] 2017-02-03 10:36
I had a similar issue using same Xcode & Swift version (XLPagerTabStrip ~> 7.0). The following worked in my case, it might help:

I implemented `ButtonBarPagerTabStripViewController` without IB, i.e. without setting up an IBOutlet to a view. My crash was caused by the `buttonBarView` not being retained. Kind of a special implementation (whose isn't?) where I removed the `buttonBarView` from the ViewController's view and manually added to the `navigationBar`.

Tried a few different solutions but ended up declaring a dummy variable to force the retain:

```
...

var buttonBarViewRetainer: UIView?

...


override func viewDidLoad() {
 
     ...

    // This will retain the buttonBarView (declared as weak) to avoid optional unwrapping crash
    buttonBarViewRetainer = buttonBarView
   
    // Custom configuration as used to work before Swift 3.0 migration
    buttonBarView.removeFromSuperview()
     ...

}
```

**Comment by santiagofm** [comment] 2017-05-17 20:10
This issue is addressed in #375 and should be merged into the master branch shortly.

**Comment by santiagofm** [comment] 2017-05-22 16:42
Fixed in #380

**Closed by santiagofm** 2017-05-22 16:42 UTC
Labels: type: issue

**Comment by Tim77277** [comment] 2018-02-21 19:06
Sorry, I just pulled the latest version and I still ran into the same problem. I went through the #375, #380 but still not be able to solve this issue. Can use some helps here if anyone can give some advise thanks.
