### ISSUE TITLE
buttonBarView.selectedBar.backgroundColor not working

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [xmartlabs/XLPagerTabStrip#275] opened 2016-11-25 10:37 UTC
buttonBarView.selectedBar.backgroundColor not working

- Environment: 
XLPagerTabStrip = 6.0.0
Xcode - 8.0
iOS - 10.0

**Comment by Aaron-zheng** [comment] 2016-12-02 02:25
i also hit this problem. any solution?

**Comment by Aaron-zheng** [comment] 2016-12-02 04:01
I jumped into the original code to check what happen. Finally I caught the root cause and found a simple solution for it now.

The root cause comes from ButtonBarView.updateSlectedBarYPosition(), it will invoke after the viewDidLoad. Actually, it should be invoke in viewDidAppear to get the actual frame.height to calculate.


**Simple solution below: in viewDidAppear() recalculate the slectedBarYPosition **

```
class ViewController: ButtonBarPagerTabStripViewController {
    
    override func viewDidAppear(_ animated: Bool) {
        let selectedBarHeight: CGFloat = 2
        
        buttonBarView.selectedBar.frame.origin.y = buttonBarView.frame.size.height - selectedBarHeight
        buttonBarView.selectedBar.frame.size.height = selectedBarHeight
        
    }
    

    override func viewDidLoad() {
        settings.style.selectedBarBackgroundColor = .green
        
        super.viewDidLoad()
    }
}
```

**Comment by mtnbarreto** [comment] 2017-01-25 21:10
Thanks for reporting it, it's already fixed in master branch.

**Closed by mtnbarreto** 2017-01-25 21:10 UTC

**Comment by Lorelei89** [comment] 2017-10-17 11:21
Hi guys
I'm using as cocapods file

pod 'XLPagerTabStrip', '~> 8.0'
use_frameworks!
end

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '4.0'
end
end
end

and i;m getting the same error on ButtonBarPagerTabStripSettings class:
buttonBarView.backgroundColor = settings.style.buttonBarBackgroundColor ??
buttonBarView.backgroundColor
buttonBarView.selectedBar.backgroundColor = settings.style.selectedBarBackgroundColor

Is someone having any sollution for this? Kind regards
