### ISSUE TITLE
clarification / feature of endless scrolling / wrapping

### ISSUE THREAD

**Issue by johndpope** [xmartlabs/XLPagerTabStrip#332] opened 2017-03-09 20:27 UTC
I'm using latest xcode / cocoapods etc

given I have 3-4 panes / vcs  - I want to have infinite scrolling such that the user can endless scroll left or right. Does any of the samples cater to this 'carousel' effect?

thanks in advance
John Pope

**Comment by johndpope** [comment] 2017-03-15 15:05
Need to glue these together - https://github.com/hryk224/InfiniteCollectionView

**Comment by m-revetria** [comment] 2017-05-03 19:47
Hi, this issue looks like a duplicate of #88. We'll take a look to how can be done.

Thanks

**Closed by m-revetria** 2017-05-03 19:47 UTC
Labels: duplicate
